### ISSUE TITLE
The directive @db(name: "<foo>") doesn't work on a field

### ISSUE THREAD

**Issue by melkir** [prisma/Mongo-Connector-Preview#11]
I have the following `datamodel.prisma`
```
type User @db(name: "users") {
  id: ID! @id
  createdAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
  email: String!
  firstName: String @db(name: "firstname")
  lastName: String @db(name: "lastname")
  slackId: String
}
```
The field `firstName` and `lastName` are always resulting to `null`.
Using a mutation to create a new User will create a document with `firstName` instead of `firstname` and `lastName` instead of `lastname`.

No problem with the following datamodel (no rename)
```
type User @db(name: "users") {
  id: ID! @id
  createdAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
  email: String!
  firstname: String
  lastname: String
  slackId: String
}
```

**Comment by do4gr** [comment]
Thanks for reporting this. I can reproduce it and am looking into fixing it.

**Comment by melkir** [comment]
Could notify me when it will be available on the prisma `alpha` branch ?
Thanks do4gr for your reactivity :)

**Comment by do4gr** [comment]
@melkir This should now work as expected on alpha.
